import { reactive } from "vue";
import { apiGet, apiPost } from "../composables/useApi.js";

export const configStore = reactive({
  form: {
    VIDEO_PATH: "",
    ROI_X0: 0,
    ROI_Y0: 0,
    ROI_X1: 0,
    ROI_Y1: 0,
    RUN_STEP_EDIT: false,
    RUN_STEP_TRANSLATE: false,
    RUN_STEP_UPSCALE: false,
    RUN_STEP_TEXT_TRANSLATE: false,
    RUN_STEP_TTS: false,
    RUN_STEP_VIDEO_EXPORT: false,
    TRANSCRIPTION_PROVIDER: "whisper",
    WHISPER_MODEL: "medium",
    WHISPER_DEVICE: "cuda",
    WHISPER_COMPUTE_TYPE: "float16",
    WHISPER_LANGUAGE: "",
    GCLOUD_PROJECT_ID: "",
    GOOGLE_SPEECH_LOCATION: "global",
    GOOGLE_SPEECH_MODEL: "chirp_3",
    GOOGLE_SPEECH_LANGUAGE_CODES: "en-US",
    GOOGLE_SPEECH_CHUNK_SEC: 55,
    GOOGLE_SPEECH_CHUNK_OVERLAP_SEC: 0.75,
    FINAL_SOURCE_MODE_AUTO: "auto",
    FULLSLIDE_SAMPLE_FRAMES: 3,
    FULLSLIDE_BORDER_STRIP_PX: 24,
    FULLSLIDE_MIN_MATCHED_SIDES: 2,
    FULLSLIDE_BORDER_DIFF_THRESHOLD: 16.0,
    FULLSLIDE_PERSON_BOX_AREA_RATIO: 0.02,
    FULLSLIDE_PERSON_OUTSIDE_RATIO: 0.35,
    KEYFRAME_SETTLE_FRAMES: 0,
    KEYFRAME_STABLE_END_GUARD_FRAMES: 0,
    KEYFRAME_STABLE_LOOKAHEAD_FRAMES: 0,
    SPEAKER_FILTER_MIN_STAGE1_VIDEO_RATIO: 0,
    SPEAKER_FILTER_MAX_EDGE_DENSITY: 0,
    SPEAKER_FILTER_MAX_LAPLACIAN_VAR: 0,
    SPEAKER_FILTER_MAX_DURATION_SEC: 0,
    FINAL_SLIDE_POSTPROCESS_MODE: "local",
    GEMINI_EDIT_MODEL: "gemini-3-pro-image-preview",
    GEMINI_EDIT_REVIEW_RETRIES: 2,
    GEMINI_EDIT_PROMPT: "",
    FINAL_SLIDE_TRANSLATION_MODE: "none",
    FINAL_SLIDE_TARGET_LANGUAGE: "",
    GEMINI_TRANSLATE_MODEL: "gemini-3-pro-image-preview",
    GEMINI_EXTRACT_MODEL: "gemini-3.1-pro-preview",
    GEMINI_SLIDE_EXTRACT_PROMPT: "",
    GEMINI_SLIDE_TRANSLATE_PROMPT: "",
    GEMINI_SLIDE_RENDER_PROMPT: "",
    SLIDE_TRANSLATE_MAX_FONT_SIZE: 120,
    SLIDE_TRANSLATE_STYLES_JSON: "",
    GOOGLE_TRANSLATE_LOCATION: "us-central1",
    TRANSCRIPT_TRANSLATE_MODEL: "gemini-2.5-pro",
    GEMINI_TEXT_TRANSLATE_PROMPT: "",
    GOOGLE_TRANSLATE_SOURCE_LANGUAGE_CODE: "",
    TRANSLATION_TERMBASE_CSV: "",
    GEMINI_TTS_MODEL: "gemini-2.5-flash-tts",
    GEMINI_TTS_VOICE: "Kore",
    GEMINI_TTS_SPEAKING_RATE: 1.0,
    GOOGLE_TTS_LANGUAGE_CODE: "",
    GEMINI_TTS_PROMPT: "",
    FINAL_SLIDE_UPSCALE_MODE: "none",
    FINAL_SLIDE_UPSCALE_MODEL: "caidas/swin2SR-classical-sr-x4-64",
    FINAL_SLIDE_UPSCALE_DEVICE: "auto",
    FINAL_SLIDE_UPSCALE_TILE_SIZE: 256,
    FINAL_SLIDE_UPSCALE_TILE_OVERLAP: 24,
    REPLICATE_NIGHTMARE_REALESRGAN_MODEL_REF: "nightmareai/real-esrgan",
    REPLICATE_NIGHTMARE_REALESRGAN_VERSION_ID: "f121d640bd286e1fdc67f9799164c1d5be36ff74576ee11c803ae5b665dd46aa",
    REPLICATE_NIGHTMARE_REALESRGAN_PRICE_PER_SECOND: 0.000225,
    REPLICATE_UPSCALE_CONCURRENCY: 2,
    VIDEO_EXPORT_MIN_SLIDE_SEC: 1.2,
    VIDEO_EXPORT_TAIL_PAD_SEC: 0.35,
    VIDEO_EXPORT_INTRO_WHITE_SEC: 1.0,
    VIDEO_EXPORT_INTRO_FADE_SEC: 0.4,
    VIDEO_EXPORT_THUMBNAIL_DURATION_SEC: 2.0,
    VIDEO_EXPORT_THUMBNAIL_FADE_SEC: 0.3,
    VIDEO_EXPORT_THUMBNAIL_TEXT_LEADIN_SEC: 1.0,
    VIDEO_EXPORT_INTRO_COLOR: "white",
    VIDEO_EXPORT_OUTRO_HOLD_SEC: 1.5,
    VIDEO_EXPORT_OUTRO_FADE_SEC: 1.5,
    VIDEO_EXPORT_OUTRO_FADE_COLOR: "black",
    VIDEO_EXPORT_OUTRO_BLACK_SEC: 2.0,
    VIDEO_EXPORT_WIDTH: 1920,
    VIDEO_EXPORT_HEIGHT: 1080,
    VIDEO_EXPORT_FPS: 30,
    VIDEO_EXPORT_BG_COLOR: "white",
  },
  ttsLanguageOptions: [],
  selectedVideoPath: "",
  configMeta: "",
  ttsLanguageSearchText: "",
  lastLoadedGoogleTranslateModel: "general/translation-llm",
});

export function setConfigFromApi(cfg) {
  const f = configStore.form;
  configStore.selectedVideoPath = cfg.VIDEO_PATH || "";
  f.VIDEO_PATH = cfg.VIDEO_PATH || "";
  f.ROI_X0 = cfg.ROI_X0 ?? 0;
  f.ROI_Y0 = cfg.ROI_Y0 ?? 0;
  f.ROI_X1 = cfg.ROI_X1 ?? 0;
  f.ROI_Y1 = cfg.ROI_Y1 ?? 0;
  f.RUN_STEP_EDIT = Boolean(cfg.RUN_STEP_EDIT);
  f.RUN_STEP_TRANSLATE = Boolean(cfg.RUN_STEP_TRANSLATE);
  f.RUN_STEP_UPSCALE = Boolean(cfg.RUN_STEP_UPSCALE);
  f.RUN_STEP_TEXT_TRANSLATE = Boolean(cfg.RUN_STEP_TEXT_TRANSLATE);
  f.RUN_STEP_TTS = Boolean(cfg.RUN_STEP_TTS);
  f.RUN_STEP_VIDEO_EXPORT = Boolean(cfg.RUN_STEP_VIDEO_EXPORT);
  f.TRANSCRIPTION_PROVIDER = cfg.TRANSCRIPTION_PROVIDER || "whisper";
  f.WHISPER_MODEL = cfg.WHISPER_MODEL || "medium";
  f.WHISPER_DEVICE = cfg.WHISPER_DEVICE || "cuda";
  f.WHISPER_COMPUTE_TYPE = cfg.WHISPER_COMPUTE_TYPE || "float16";
  f.WHISPER_LANGUAGE = cfg.WHISPER_LANGUAGE || "";
  f.GCLOUD_PROJECT_ID = cfg.GCLOUD_PROJECT_ID
    || cfg.GCLOUD_VERTEX_PROJECTID
    || cfg.GOOGLE_GEMINI_PROJECT_ID
    || cfg.GCLOUD_VISION_PROJECTID
    || cfg.GOOGLE_VISION_PROJECT_ID
    || cfg.GCLOUD_TRANSLATE_PROJECTID
    || cfg.GOOGLE_TRANSLATE_PROJECT_ID
    || cfg.GCLOUD_TTS_PROJECTID
    || cfg.GOOGLE_TTS_PROJECT_ID
    || cfg.GOOGLE_SPEECH_PROJECT_ID
    || "";
  f.GOOGLE_SPEECH_LOCATION = cfg.GOOGLE_SPEECH_LOCATION || "global";
  f.GOOGLE_SPEECH_MODEL = cfg.GOOGLE_SPEECH_MODEL || "chirp_3";
  f.GOOGLE_SPEECH_LANGUAGE_CODES = cfg.GOOGLE_SPEECH_LANGUAGE_CODES || "en-US";
  f.GOOGLE_SPEECH_CHUNK_SEC = cfg.GOOGLE_SPEECH_CHUNK_SEC ?? 55;
  f.GOOGLE_SPEECH_CHUNK_OVERLAP_SEC = cfg.GOOGLE_SPEECH_CHUNK_OVERLAP_SEC ?? 0.75;
  f.FINAL_SOURCE_MODE_AUTO = cfg.FINAL_SOURCE_MODE_AUTO || "auto";
  f.FULLSLIDE_SAMPLE_FRAMES = cfg.FULLSLIDE_SAMPLE_FRAMES ?? 3;
  f.FULLSLIDE_BORDER_STRIP_PX = cfg.FULLSLIDE_BORDER_STRIP_PX ?? 24;
  f.FULLSLIDE_MIN_MATCHED_SIDES = cfg.FULLSLIDE_MIN_MATCHED_SIDES ?? 2;
  f.FULLSLIDE_BORDER_DIFF_THRESHOLD = cfg.FULLSLIDE_BORDER_DIFF_THRESHOLD ?? 16.0;
  f.FULLSLIDE_PERSON_BOX_AREA_RATIO = cfg.FULLSLIDE_PERSON_BOX_AREA_RATIO ?? 0.02;
  f.FULLSLIDE_PERSON_OUTSIDE_RATIO = cfg.FULLSLIDE_PERSON_OUTSIDE_RATIO ?? 0.35;
  f.KEYFRAME_SETTLE_FRAMES = cfg.KEYFRAME_SETTLE_FRAMES ?? 0;
  f.KEYFRAME_STABLE_END_GUARD_FRAMES = cfg.KEYFRAME_STABLE_END_GUARD_FRAMES ?? 0;
  f.KEYFRAME_STABLE_LOOKAHEAD_FRAMES = cfg.KEYFRAME_STABLE_LOOKAHEAD_FRAMES ?? 0;
  f.SPEAKER_FILTER_MIN_STAGE1_VIDEO_RATIO = cfg.SPEAKER_FILTER_MIN_STAGE1_VIDEO_RATIO ?? 0;
  f.SPEAKER_FILTER_MAX_EDGE_DENSITY = cfg.SPEAKER_FILTER_MAX_EDGE_DENSITY ?? 0;
  f.SPEAKER_FILTER_MAX_LAPLACIAN_VAR = cfg.SPEAKER_FILTER_MAX_LAPLACIAN_VAR ?? 0;
  f.SPEAKER_FILTER_MAX_DURATION_SEC = cfg.SPEAKER_FILTER_MAX_DURATION_SEC ?? 0;
  f.FINAL_SLIDE_POSTPROCESS_MODE = cfg.FINAL_SLIDE_POSTPROCESS_MODE || "local";
  f.GEMINI_EDIT_MODEL = cfg.GEMINI_EDIT_MODEL || "gemini-3-pro-image-preview";
  f.GEMINI_EDIT_REVIEW_RETRIES = cfg.GEMINI_EDIT_REVIEW_RETRIES ?? 2;
  f.GEMINI_EDIT_PROMPT = cfg.GEMINI_EDIT_PROMPT || "";
  f.FINAL_SLIDE_TRANSLATION_MODE = cfg.FINAL_SLIDE_TRANSLATION_MODE || "none";
  f.FINAL_SLIDE_TARGET_LANGUAGE = cfg.FINAL_SLIDE_TARGET_LANGUAGE || "";
  f.GEMINI_TRANSLATE_MODEL = cfg.GEMINI_TRANSLATE_MODEL || "gemini-3-pro-image-preview";
  f.GEMINI_EXTRACT_MODEL = cfg.GEMINI_EXTRACT_MODEL || "gemini-3.1-pro-preview";
  f.GEMINI_SLIDE_EXTRACT_PROMPT = cfg.GEMINI_SLIDE_EXTRACT_PROMPT || "";
  f.GEMINI_SLIDE_TRANSLATE_PROMPT = cfg.GEMINI_SLIDE_TRANSLATE_PROMPT || "";
  f.GEMINI_SLIDE_RENDER_PROMPT = cfg.GEMINI_SLIDE_RENDER_PROMPT || "";
  f.SLIDE_TRANSLATE_MAX_FONT_SIZE = cfg.SLIDE_TRANSLATE_MAX_FONT_SIZE ?? 120;
  f.SLIDE_TRANSLATE_STYLES_JSON = cfg.SLIDE_TRANSLATE_STYLES_JSON || "";
  f.GOOGLE_TRANSLATE_LOCATION = cfg.GOOGLE_TRANSLATE_LOCATION || "us-central1";
  f.TRANSCRIPT_TRANSLATE_MODEL = cfg.TRANSCRIPT_TRANSLATE_MODEL || "gemini-2.5-pro";
  f.GEMINI_TEXT_TRANSLATE_PROMPT = cfg.GEMINI_TEXT_TRANSLATE_PROMPT || "";
  f.GOOGLE_TRANSLATE_SOURCE_LANGUAGE_CODE = cfg.GOOGLE_TRANSLATE_SOURCE_LANGUAGE_CODE || "";
  f.TRANSLATION_TERMBASE_CSV = cfg.TRANSLATION_TERMBASE_CSV || "";
  f.GEMINI_TTS_MODEL = cfg.GEMINI_TTS_MODEL || "gemini-2.5-flash-tts";
  f.GEMINI_TTS_VOICE = cfg.GEMINI_TTS_VOICE || "Kore";
  f.GEMINI_TTS_SPEAKING_RATE = cfg.GEMINI_TTS_SPEAKING_RATE ?? 1.0;
  f.GOOGLE_TTS_LANGUAGE_CODE = cfg.GOOGLE_TTS_LANGUAGE_CODE || "";
  f.GEMINI_TTS_PROMPT = cfg.GEMINI_TTS_PROMPT || "";
  f.FINAL_SLIDE_UPSCALE_MODE = cfg.FINAL_SLIDE_UPSCALE_MODE || "none";
  f.FINAL_SLIDE_UPSCALE_MODEL = cfg.FINAL_SLIDE_UPSCALE_MODEL || "caidas/swin2SR-classical-sr-x4-64";
  f.FINAL_SLIDE_UPSCALE_DEVICE = cfg.FINAL_SLIDE_UPSCALE_DEVICE || "auto";
  f.FINAL_SLIDE_UPSCALE_TILE_SIZE = cfg.FINAL_SLIDE_UPSCALE_TILE_SIZE ?? 256;
  f.FINAL_SLIDE_UPSCALE_TILE_OVERLAP = cfg.FINAL_SLIDE_UPSCALE_TILE_OVERLAP ?? 24;
  f.REPLICATE_NIGHTMARE_REALESRGAN_MODEL_REF = cfg.REPLICATE_NIGHTMARE_REALESRGAN_MODEL_REF || "nightmareai/real-esrgan";
  f.REPLICATE_NIGHTMARE_REALESRGAN_VERSION_ID = cfg.REPLICATE_NIGHTMARE_REALESRGAN_VERSION_ID || "f121d640bd286e1fdc67f9799164c1d5be36ff74576ee11c803ae5b665dd46aa";
  f.REPLICATE_NIGHTMARE_REALESRGAN_PRICE_PER_SECOND = cfg.REPLICATE_NIGHTMARE_REALESRGAN_PRICE_PER_SECOND ?? 0.000225;
  f.REPLICATE_UPSCALE_CONCURRENCY = cfg.REPLICATE_UPSCALE_CONCURRENCY ?? 2;
  f.VIDEO_EXPORT_MIN_SLIDE_SEC = cfg.VIDEO_EXPORT_MIN_SLIDE_SEC ?? 1.2;
  f.VIDEO_EXPORT_TAIL_PAD_SEC = cfg.VIDEO_EXPORT_TAIL_PAD_SEC ?? 0.35;
  f.VIDEO_EXPORT_INTRO_WHITE_SEC = cfg.VIDEO_EXPORT_INTRO_WHITE_SEC ?? 1.0;
  f.VIDEO_EXPORT_INTRO_FADE_SEC = cfg.VIDEO_EXPORT_INTRO_FADE_SEC ?? 0.4;
  f.VIDEO_EXPORT_THUMBNAIL_DURATION_SEC = cfg.VIDEO_EXPORT_THUMBNAIL_DURATION_SEC ?? 2.0;
  f.VIDEO_EXPORT_THUMBNAIL_FADE_SEC = cfg.VIDEO_EXPORT_THUMBNAIL_FADE_SEC ?? 0.3;
  f.VIDEO_EXPORT_THUMBNAIL_TEXT_LEADIN_SEC = cfg.VIDEO_EXPORT_THUMBNAIL_TEXT_LEADIN_SEC ?? 1.0;
  f.VIDEO_EXPORT_INTRO_COLOR = cfg.VIDEO_EXPORT_INTRO_COLOR || "white";
  f.VIDEO_EXPORT_OUTRO_HOLD_SEC = cfg.VIDEO_EXPORT_OUTRO_HOLD_SEC ?? 1.5;
  f.VIDEO_EXPORT_OUTRO_FADE_SEC = cfg.VIDEO_EXPORT_OUTRO_FADE_SEC ?? 1.5;
  f.VIDEO_EXPORT_OUTRO_FADE_COLOR = cfg.VIDEO_EXPORT_OUTRO_FADE_COLOR || "black";
  f.VIDEO_EXPORT_OUTRO_BLACK_SEC = cfg.VIDEO_EXPORT_OUTRO_BLACK_SEC ?? 2.0;
  f.VIDEO_EXPORT_WIDTH = cfg.VIDEO_EXPORT_WIDTH ?? 1920;
  f.VIDEO_EXPORT_HEIGHT = cfg.VIDEO_EXPORT_HEIGHT ?? 1080;
  f.VIDEO_EXPORT_FPS = cfg.VIDEO_EXPORT_FPS ?? 30;
  f.VIDEO_EXPORT_BG_COLOR = cfg.VIDEO_EXPORT_BG_COLOR || "white";

  configStore.ttsLanguageOptions = Array.isArray(cfg.GEMINI_TTS_LANGUAGE_OPTIONS) ? cfg.GEMINI_TTS_LANGUAGE_OPTIONS : [];
  configStore.ttsLanguageSearchText = "";
  configStore.lastLoadedGoogleTranslateModel = String(cfg.GOOGLE_TRANSLATE_MODEL || "general/translation-llm").trim();

  const videoLabel = cfg.VIDEO_PATH || "(nicht gesetzt)";
  configStore.configMeta = `VIDEO_PATH: ${videoLabel}`;

  document.dispatchEvent(new CustomEvent("health-clear-all"));
}

function buildSavePayload() {
  const f = configStore.form;
  const gcloudProjectId = String(f.GCLOUD_PROJECT_ID || "").trim();
  const selectedOption = findTtsLanguageOptionByCode(f.GOOGLE_TTS_LANGUAGE_CODE);
  return {
    VIDEO_PATH: (configStore.selectedVideoPath || "").trim(),
    ROI_X0: Number(f.ROI_X0),
    ROI_Y0: Number(f.ROI_Y0),
    ROI_X1: Number(f.ROI_X1),
    ROI_Y1: Number(f.ROI_Y1),
    RUN_STEP_EDIT: f.RUN_STEP_EDIT ? 1 : 0,
    RUN_STEP_TRANSLATE: f.RUN_STEP_TRANSLATE ? 1 : 0,
    RUN_STEP_UPSCALE: f.RUN_STEP_UPSCALE ? 1 : 0,
    RUN_STEP_TEXT_TRANSLATE: f.RUN_STEP_TEXT_TRANSLATE ? 1 : 0,
    RUN_STEP_TTS: f.RUN_STEP_TTS ? 1 : 0,
    RUN_STEP_VIDEO_EXPORT: f.RUN_STEP_VIDEO_EXPORT ? 1 : 0,
    TRANSCRIPTION_PROVIDER: f.TRANSCRIPTION_PROVIDER,
    WHISPER_MODEL: String(f.WHISPER_MODEL || "").trim(),
    WHISPER_DEVICE: String(f.WHISPER_DEVICE || "").trim(),
    WHISPER_COMPUTE_TYPE: String(f.WHISPER_COMPUTE_TYPE || "").trim(),
    WHISPER_LANGUAGE: String(f.WHISPER_LANGUAGE || "").trim(),
    GCLOUD_PROJECT_ID: gcloudProjectId,
    GOOGLE_SPEECH_PROJECT_ID: gcloudProjectId,
    GOOGLE_SPEECH_LOCATION: String(f.GOOGLE_SPEECH_LOCATION || "").trim(),
    GOOGLE_SPEECH_MODEL: String(f.GOOGLE_SPEECH_MODEL || "").trim(),
    GOOGLE_SPEECH_LANGUAGE_CODES: String(f.GOOGLE_SPEECH_LANGUAGE_CODES || "").trim(),
    GOOGLE_SPEECH_CHUNK_SEC: Number(f.GOOGLE_SPEECH_CHUNK_SEC),
    GOOGLE_SPEECH_CHUNK_OVERLAP_SEC: Number(f.GOOGLE_SPEECH_CHUNK_OVERLAP_SEC),
    FINAL_SOURCE_MODE_AUTO: f.FINAL_SOURCE_MODE_AUTO,
    FULLSLIDE_SAMPLE_FRAMES: Number(f.FULLSLIDE_SAMPLE_FRAMES),
    FULLSLIDE_BORDER_STRIP_PX: Number(f.FULLSLIDE_BORDER_STRIP_PX),
    FULLSLIDE_MIN_MATCHED_SIDES: Number(f.FULLSLIDE_MIN_MATCHED_SIDES),
    FULLSLIDE_BORDER_DIFF_THRESHOLD: Number(f.FULLSLIDE_BORDER_DIFF_THRESHOLD),
    FULLSLIDE_PERSON_BOX_AREA_RATIO: Number(f.FULLSLIDE_PERSON_BOX_AREA_RATIO),
    FULLSLIDE_PERSON_OUTSIDE_RATIO: Number(f.FULLSLIDE_PERSON_OUTSIDE_RATIO),
    KEYFRAME_SETTLE_FRAMES: Number(f.KEYFRAME_SETTLE_FRAMES),
    KEYFRAME_STABLE_END_GUARD_FRAMES: Number(f.KEYFRAME_STABLE_END_GUARD_FRAMES),
    KEYFRAME_STABLE_LOOKAHEAD_FRAMES: Number(f.KEYFRAME_STABLE_LOOKAHEAD_FRAMES),
    SPEAKER_FILTER_MIN_STAGE1_VIDEO_RATIO: Number(f.SPEAKER_FILTER_MIN_STAGE1_VIDEO_RATIO),
    SPEAKER_FILTER_MAX_EDGE_DENSITY: Number(f.SPEAKER_FILTER_MAX_EDGE_DENSITY),
    SPEAKER_FILTER_MAX_LAPLACIAN_VAR: Number(f.SPEAKER_FILTER_MAX_LAPLACIAN_VAR),
    SPEAKER_FILTER_MAX_DURATION_SEC: Number(f.SPEAKER_FILTER_MAX_DURATION_SEC),
    FINAL_SLIDE_POSTPROCESS_MODE: f.FINAL_SLIDE_POSTPROCESS_MODE,
    GEMINI_EDIT_MODEL: String(f.GEMINI_EDIT_MODEL || "").trim(),
    GEMINI_EDIT_REVIEW_RETRIES: Number(f.GEMINI_EDIT_REVIEW_RETRIES),
    GEMINI_EDIT_PROMPT: f.GEMINI_EDIT_PROMPT,
    FINAL_SLIDE_TRANSLATION_MODE: f.FINAL_SLIDE_TRANSLATION_MODE,
    FINAL_SLIDE_TARGET_LANGUAGE: (selectedOption?.label || "").trim(),
    GEMINI_TRANSLATE_MODEL: String(f.GEMINI_TRANSLATE_MODEL || "").trim(),
    GEMINI_EXTRACT_MODEL: String(f.GEMINI_EXTRACT_MODEL || "").trim(),
    GEMINI_SLIDE_EXTRACT_PROMPT: f.GEMINI_SLIDE_EXTRACT_PROMPT,
    GEMINI_SLIDE_TRANSLATE_PROMPT: f.GEMINI_SLIDE_TRANSLATE_PROMPT,
    GEMINI_SLIDE_RENDER_PROMPT: f.GEMINI_SLIDE_RENDER_PROMPT,
    GCLOUD_VISION_PROJECTID: gcloudProjectId,
    GOOGLE_VISION_PROJECT_ID: gcloudProjectId,
    GCLOUD_VERTEX_PROJECTID: gcloudProjectId,
    GOOGLE_GEMINI_PROJECT_ID: gcloudProjectId,
    SLIDE_TRANSLATE_MAX_FONT_SIZE: Number(f.SLIDE_TRANSLATE_MAX_FONT_SIZE),
    SLIDE_TRANSLATE_STYLES_JSON: f.SLIDE_TRANSLATE_STYLES_JSON,
    GCLOUD_TRANSLATE_PROJECTID: gcloudProjectId,
    GOOGLE_TRANSLATE_PROJECT_ID: gcloudProjectId,
    GOOGLE_TRANSLATE_LOCATION: String(f.GOOGLE_TRANSLATE_LOCATION || "").trim(),
    GOOGLE_TRANSLATE_MODEL: configStore.lastLoadedGoogleTranslateModel,
    TRANSCRIPT_TRANSLATE_MODEL: String(f.TRANSCRIPT_TRANSLATE_MODEL || "").trim(),
    GEMINI_TEXT_TRANSLATE_PROMPT: f.GEMINI_TEXT_TRANSLATE_PROMPT,
    GOOGLE_TRANSLATE_SOURCE_LANGUAGE_CODE: String(f.GOOGLE_TRANSLATE_SOURCE_LANGUAGE_CODE || "").trim(),
    TRANSLATION_TERMBASE_CSV: f.TRANSLATION_TERMBASE_CSV,
    GEMINI_TTS_MODEL: String(f.GEMINI_TTS_MODEL || "").trim(),
    GEMINI_TTS_VOICE: String(f.GEMINI_TTS_VOICE || "").trim(),
    GEMINI_TTS_SPEAKING_RATE: Number(f.GEMINI_TTS_SPEAKING_RATE),
    GCLOUD_TTS_PROJECTID: gcloudProjectId,
    GOOGLE_TTS_PROJECT_ID: gcloudProjectId,
    GOOGLE_TTS_LANGUAGE_CODE: (selectedOption?.tts_language_code || "").trim(),
    GEMINI_TTS_PROMPT: f.GEMINI_TTS_PROMPT,
    FINAL_SLIDE_UPSCALE_MODE: f.FINAL_SLIDE_UPSCALE_MODE,
    FINAL_SLIDE_UPSCALE_MODEL: String(f.FINAL_SLIDE_UPSCALE_MODEL || "").trim(),
    FINAL_SLIDE_UPSCALE_DEVICE: f.FINAL_SLIDE_UPSCALE_DEVICE,
    FINAL_SLIDE_UPSCALE_TILE_SIZE: Number(f.FINAL_SLIDE_UPSCALE_TILE_SIZE),
    FINAL_SLIDE_UPSCALE_TILE_OVERLAP: Number(f.FINAL_SLIDE_UPSCALE_TILE_OVERLAP),
    REPLICATE_NIGHTMARE_REALESRGAN_MODEL_REF: String(f.REPLICATE_NIGHTMARE_REALESRGAN_MODEL_REF || "").trim(),
    REPLICATE_NIGHTMARE_REALESRGAN_VERSION_ID: String(f.REPLICATE_NIGHTMARE_REALESRGAN_VERSION_ID || "").trim(),
    REPLICATE_NIGHTMARE_REALESRGAN_PRICE_PER_SECOND: Number(f.REPLICATE_NIGHTMARE_REALESRGAN_PRICE_PER_SECOND),
    REPLICATE_UPSCALE_CONCURRENCY: Number(f.REPLICATE_UPSCALE_CONCURRENCY),
    VIDEO_EXPORT_MIN_SLIDE_SEC: Number(f.VIDEO_EXPORT_MIN_SLIDE_SEC),
    VIDEO_EXPORT_TAIL_PAD_SEC: Number(f.VIDEO_EXPORT_TAIL_PAD_SEC),
    VIDEO_EXPORT_INTRO_WHITE_SEC: Number(f.VIDEO_EXPORT_INTRO_WHITE_SEC),
    VIDEO_EXPORT_INTRO_FADE_SEC: Number(f.VIDEO_EXPORT_INTRO_FADE_SEC),
    VIDEO_EXPORT_THUMBNAIL_DURATION_SEC: Number(f.VIDEO_EXPORT_THUMBNAIL_DURATION_SEC),
    VIDEO_EXPORT_THUMBNAIL_FADE_SEC: Number(f.VIDEO_EXPORT_THUMBNAIL_FADE_SEC),
    VIDEO_EXPORT_THUMBNAIL_TEXT_LEADIN_SEC: Number(f.VIDEO_EXPORT_THUMBNAIL_TEXT_LEADIN_SEC),
    VIDEO_EXPORT_INTRO_COLOR: String(f.VIDEO_EXPORT_INTRO_COLOR || "").trim(),
    VIDEO_EXPORT_OUTRO_HOLD_SEC: Number(f.VIDEO_EXPORT_OUTRO_HOLD_SEC),
    VIDEO_EXPORT_OUTRO_FADE_SEC: Number(f.VIDEO_EXPORT_OUTRO_FADE_SEC),
    VIDEO_EXPORT_OUTRO_FADE_COLOR: String(f.VIDEO_EXPORT_OUTRO_FADE_COLOR || "").trim(),
    VIDEO_EXPORT_OUTRO_BLACK_SEC: Number(f.VIDEO_EXPORT_OUTRO_BLACK_SEC),
    VIDEO_EXPORT_WIDTH: Number(f.VIDEO_EXPORT_WIDTH),
    VIDEO_EXPORT_HEIGHT: Number(f.VIDEO_EXPORT_HEIGHT),
    VIDEO_EXPORT_FPS: Number(f.VIDEO_EXPORT_FPS),
    VIDEO_EXPORT_BG_COLOR: String(f.VIDEO_EXPORT_BG_COLOR || "").trim(),
  };
}

export async function loadConfig() {
  const cfg = await apiGet("/api/config");
  setConfigFromApi(cfg);
  return cfg;
}

export async function saveConfig() {
  configStore.form.VIDEO_PATH = configStore.selectedVideoPath;
  const payload = buildSavePayload();
  await apiPost("/api/config", payload);
  return await loadConfig();
}

// --- TTS language helpers (moved from tts-language.js) ---

export function normalizeLanguageSearch(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim();
}

export function findTtsLanguageOptionByCode(code) {
  const wanted = String(code || "").trim();
  if (!wanted) return null;
  const options = configStore.ttsLanguageOptions;
  return options.find((item) => item.tts_language_code === wanted) || null;
}

export function filteredTtsLanguageOptions(filterText = "") {
  const query = normalizeLanguageSearch(filterText);
  const all = configStore.ttsLanguageOptions;
  if (!query) return all;
  return all.filter((item) => {
    const readiness = normalizeLanguageSearch(item.launch_readiness || "");
    const label = normalizeLanguageSearch(item.label || "");
    const code = normalizeLanguageSearch(item.tts_language_code || "");
    return label.includes(query) || code.includes(query) || readiness.includes(query);
  });
}

// --- Utility helpers ---

export function videoThumbUrl(videoPath) {
  return `/api/videos/thumbnail?path=${encodeURIComponent(videoPath)}&v=${Date.now()}`;
}

export function formatUsd(value) {
  const num = Number(value || 0);
  if (!(num > 0)) return "-";
  return `$${num.toFixed(4)}`;
}

export function formatRunIdLabel(runId) {
  const raw = String(runId || "").trim();
  const match = raw.match(/^(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})(?:-(\d{2}))?$/);
  if (!match) return raw || "-";
  const [, year, month, day, hour, minute] = match;
  const monthNames = {
    "01": "Jan", "02": "Feb", "03": "Mar", "04": "Apr",
    "05": "May", "06": "Jun", "07": "Jul", "08": "Aug",
    "09": "Sep", "10": "Oct", "11": "Nov", "12": "Dec",
  };
  return `${day}-${monthNames[month] || month}-${year}, ${hour}:${minute}`;
}
