export const state = {
  selectedRunId: null,
  latestRunId: null,
  latestRunDetail: null,
  currentRunId: null,
  selectedVideoPath: "",
  videoItems: [],
  labImages: [],
  labSelectedImage: null,
  latestCsvLines: [],
  latestCsvExpanded: false,
  latestSlidesMode: "final",
  latestFinalSourceMode: "processed",
  latestFinalDisplayMode: "single",
  latestFinalResolutionMode: "native",
  runFinalSourceMode: "processed",
  runFinalDisplayMode: "single",
  runFinalResolutionMode: "native",
  lastSettledRefreshKey: "",
  currentRunStatus: "idle",
  labStatus: "idle",
  stepSectionExpanded: {},
  ttsLanguageOptions: [],
};
