export const state = {
  selectedRunId: null,
  latestRunId: null,
  latestRunDetail: null,
  currentRunId: null,
  selectedVideoPath: "",
  videoItems: [],
  latestInfoExpanded: false,
  latestSlidesMode: "final",
  latestFinalSourceMode: "processed",
  latestFinalDisplayMode: "single",
  latestShowOriginalText: true,
  runSlidesMode: "final",
  runFinalSourceMode: "processed",
  runFinalDisplayMode: "single",
  runShowOriginalText: true,
  lastSettledRefreshKey: "",
  currentRunStatus: "idle",
  stepSectionExpanded: {},
  ttsLanguageOptions: [],
};
